[package]
name = "simple_reactor"
version = "0.1.0"
edition = "2024"

[dependencies]
mio = { version = "1.0.4", features = ["os-poll", "net"] }
slab = "0.4.10"
bytes = "1.8.0"
log = "0.4"
env_logger = "0.10"